name = "CESM"
uuid = "9b356d87-214f-4bb0-973e-00fda133217d"
version = "0.1.0"
authors = ["Sina Hajikazemi <sina.hkazemi@gmail.com>"]

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Dualization = "191a621a-6537-11e9-281d-650236a99e60"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
Gurobi = "2e9cd046-0924-5485-92f1-d5272153d98b"
HiGHS = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LoggingExtras = "e6f89c97-d47a-5376-807f-9c37f3926c36"
PrettyPrinting = "54e16d92-306c-5ea0-a30b-337be88ac337"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SankeyMakie = "1323c716-dab9-4207-0457-9cc5295a221b"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
cuOpt = "29a73d17-8276-40b7-9ffb-d89e58023643"

[compat]
CSV = "0.10.15"
CairoMakie = "0.13.10"
Dualization = "0.7.1"
GLMakie = "0.11.11"
Gurobi = "1.6.3"
HiGHS = "1.13.0"
Ipopt = "1.11.0"
JSON = "0.21.4"
JuMP = "1.24.0"
LoggingExtras = "1.2.0"
PrettyPrinting = "0.4.2"
PrettyTables = "3.1.2"
Revise = "3.8.0"
SankeyMakie = "0.1.1"
StatsPlots = "0.15.7"
Test = "1.11.0"
cuOpt = "0.1.1"
